### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by op1umseller** [RickyTheRacc/banana-for-everyone#27]
### Describe the feature

Could you please keep the 1.18 version? 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by Aholicknight** [comment]
Lmao what

**Comment by Munchax10** [comment]
> Lmao what

Hes sayin to keep the old downloads
