### ISSUE TITLE
[Suggestion] Please add an config to only use sword gap (on monkhand) when you're right clicking with the sword

### ISSUE THREAD

**Issue by Olokw** [RickyTheRacc/banana-for-everyone#30]
### Describe the feature

An setting on the monkhand, which restricts the sword gap to only use when you are right clicking.

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by I-Got-You-Dead** [comment]
Do it yourself

**Comment by Olokw** [comment]
Every 1.12 cpvp client have this, so why not? this addon is the best for cpvp at 1.16+. Can't you add this feature to the addon?
