### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by eimaaat** [RickyTheRacc/banana-for-everyone#31]
### Describe the feature

can you please add auto item frame duper and the auto salc1 duper module 

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest release**)

- [X] This wasn't already suggested.
(I have checked all of the other suggestions)

**Comment by I-Got-You-Dead** [comment]
🤡
