### ISSUE TITLE
[Bug] Game crashes when trying to put armor on. True for the latest rewrite version.

### ISSUE THREAD

**Issue by Anonimouze** [RickyTheRacc/banana-for-everyone#33]
### Describe the Bug

Fix it. Anyways nice addon. Can you bring bind click extra back? It was a very nice module.

### Steps to Reproduce

```bash
Put on a armor the game will crash
```

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub.)

- [X] This is a valid bug.
(This happens on the latest release.)

**Comment by RickyTheRacc** [comment]
You are the first one to notice the rewrite branches btw good job

**Comment by Anonimouze** [comment]
> You are the first one to notice the rewrite branches btw good job

Thank you. Also nice client but 

> You are the first one to notice the rewrite branches btw good job



> You are the first one to notice the rewrite branches btw good job

Thank you. Also which branch are you continuing now rewrite or take-2?

**Comment by RickyTheRacc** [comment]
Likely take-2, rewrite had some good stuff but it was getting messy and out of hand

**Comment by Anonimouze** [comment]
> Likely take-2, rewrite had some good stuff but it was getting messy and out of hand

Okay thanks. Also i would likely recommend re-adding the bindclickextra perhaps as a macros option. It was really good and I have not seen any other clients do it before. Correct me if its not possible.

**Comment by Anonimouze** [comment]
Also do you know how to build the latest rewrite or take-2 version? When I try to build either it gives this error: > Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.5/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 10s
1 actionable task: 1 executed
